apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: postgres-pod
      labels:
        type: persistent-db
    spec:
      containers:
        - name: postgres-container
          image: postgres
  selector:
    matchLabels:
      type: persistent-db