apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-demo-app
spec:
  template:
    metadata:
      name: redis-pod
      labels:
        app: memory-keyvalue
    spec:
      containers:
        - name: redis-container
          image: redis:alpine
          ports:
          - containerPort: 6379
  replicas: 1
  selector:
    matchLabels:
      app: memory-keyvalue