apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-demo
spec:
  template:
    metadata:
      name: result-pod
      labels:
        type: result
    spec:
      containers:
        - name: result-container
          image: dockersamples/examplevotingapp_result
  replicas: 1
  selector:
    matchLabels:
      type: result