apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-demo-app
spec:
  template:
    metadata:
      name: worker-pod
      labels:
        type: processing
    spec:
      containers:
        - name: worker-container
          image: dockersamples/examplevotingapp_worker
  replicas: 1
  selector:
    matchLabels:
      type: processing
